import { detailAuthoringReference, RELAYER_ICON_NAMES } from "@relayer/graph-client";

export const GRAPH_PRESENTATION_GUIDANCE = `Graph presentation guidance:
Available presentation capabilities: authored HTML/CSS can express layout, diagrams, comparisons, and other visual explanations without image files. Graph actions provide navigation and supported controls. The visual-assets API can discover, register, and bind images when needed. Asset inspection resolves metadata and preview files; seeing those files requires the selected harness and model to support native image inspection. Use the language-specific public API recipes below.
- Each layer should explain its scope as a coherent whole. The root layer should let the user understand the overall problem or task, the material work or logic, and the result, evidence, or limitations that matter. A child layer should do the same for the narrower scope it owns.
- Choose "expand" when another layer should deepen one part of the current explanation. Each expansion should add a useful level of detail rather than merely restating its parent.
- Choose "reference" for supporting evidence or reusable context that helps the current explanation but is not part of its decomposition. A layer reached as a reference may author only further reference actions; it must not author expand or invoke actions.
- Choose "invoke" when the useful next step requires a new agent interaction. Do not use invoke as a substitute for explanation that belongs in the current graph.
- Choose "input" when the user should provide a bounded text, single-select, or multi-select value for their next ordinary interaction. Input is optional authored UI, not an invoke, navigation target, required field, or independent task. Use stable option keys and concise prompts; do not add one to every node.
- In this presentation-choice guidance only, choosing "stop" means leaving the node without a further action because expand, reference, and invoke would not materially improve understanding or help the user proceed. It is not GraphComplete's stopped lifecycle state and does not stop the interaction: you must still finish the response with a successful graph.submit call.`;

export const CURRENT_WORKSPACE_GUIDANCE = `You may be working in a graph with other live agents. Treat the graph as a live, user-facing workspace rather than only a final response format. Your current pointer communicates where your work presently stands before completion; consider updating it as the work evolves. Advancing current does not complete the interaction. Final graph submission completes it.
Publication contract: construct nodes, layers, and actions with stable client keys. Bind detail controls to the same action objects and exact containing source layer before checkpointing details. Submit nodes, edges, and layers, then register ALL actions for the closure, including the interaction root expand action. Only after those writes may you advance current to the root layer. Do not advance child layers before connecting them. Advancing current accepts the published closure: its nodes, layers, and actions become immutable. It is not a draft preview. Do not add actions or edit published nodes afterward; author new records for changed content while preserving access to prior current. A fresh object with the same key can repair a draft, but cannot edit an accepted record. Advancing is optional; final graph.submit remains required.
Public visual authoring reference (generated from the compiler; no source inspection needed): ${JSON.stringify(detailAuthoringReference())}
Valid node icons: ${RELAYER_ICON_NAMES.join(", ")}.
Use CSS custom properties and the listed properties/functions; allowed names still have value and selector validation. Inline SVG, canvas, scripts, event handlers, arbitrary data attributes, raw URL attributes, background images, and gradients are unsupported. Use HTML/CSS shapes or registered image assets. Bind asset and control attributes through the public template API, not strings. Runtime control state comes from graph actions, not authored attributes: runtimeOwnedAttributes are prohibited even if also listed for an element. Checkpoint errors identify the component and rejected construct; repair that specific draft before publication.`;
