// Generates the renderer's design tokens and fonts from a design config (design-config-plan.md §2).
// RELAYER_DESIGN selects a config by id (designs/<id>.json) or path; otherwise designs/default names it.
import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadStructure, validateDesign } from "./validate.mjs";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const fontsDirectory = resolve(repositoryRoot, "designs/fonts");
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

export async function resolveDesignPath(selection = process.env.RELAYER_DESIGN) {
  const id = selection || (await readFile(resolve(repositoryRoot, "designs/default"), "utf8")).trim();
  return id.endsWith(".json") ? resolve(process.env.INIT_CWD ?? process.cwd(), id) : resolve(repositoryRoot, "designs", `${id}.json`);
}

// Font roles (ui, display, mono) named by the structure, with their committed files and licence.
export async function loadDesignFonts(structure) {
  return Promise.all(Object.entries(structure.fonts ?? {}).map(async ([role, id]) => {
    const font = JSON.parse(await readFile(resolve(fontsDirectory, id, "font.json"), "utf8"));
    const files = await Promise.all([...font.faces.map((face) => face.file), font.licenseFile].map(async (file) => {
      const bytes = await readFile(resolve(fontsDirectory, id, file));
      const face = font.faces.find((candidate) => candidate.file === file);
      if (face && sha256(bytes) !== face.sha256) throw new Error(`Font ${id}/${file} does not match its recorded sha256.`);
      return { path: `design/fonts/${id}/${file}`, bytes };
    }));
    return { role, id, font, files };
  }));
}

export function designCss(config, source, fonts = []) {
  const block = (mode) => [
    ...Object.entries(config.palette.roles).map(([role, value]) => `--${role}:${value[mode]}`),
    ...Object.entries(config.palette.families).flatMap(([id, family]) => [
      `--family-${id}:${family[mode]}`,
      `--family-${id}-icon:${family[`${mode}Icon`]}`,
    ]),
    `color-scheme:${mode}`,
  ].join(";");
  const faces = fonts.flatMap(({ id, font }) => font.faces.map((face) => `@font-face{font-family:"${font.family}";`
    + `src:url("./fonts/${id}/${face.file}") format("woff2");font-weight:${face.weight};font-style:${face.style};`
    + `font-display:swap;unicode-range:${face.unicodeRange}}`));
  const families = fonts.map(({ role, font }) => `--font-${role}:"${font.family}",${font.fallback}`).join(";");
  return `/* Generated by scripts/design/build.mjs from ${source}. Do not edit. */\n`
    + faces.map((face) => `${face}\n`).join("")
    + (families ? `:root{${families}}\n` : "")
    + `:root{${block("dark")}}\n:root[data-theme="light"]{${block("light")}}\n`;
}

// The files the build writes, relative to desktop/renderer, for artifacts that must ship them.
export async function designOutputFiles(selection) {
  const config = JSON.parse(await readFile(await resolveDesignPath(selection), "utf8"));
  const fonts = await loadDesignFonts(await loadStructure(config.structure));
  return ["design/design.css", ...fonts.flatMap((font) => font.files.map((file) => file.path))];
}

export async function buildDesign({ selection, outputDirectory = resolve(repositoryRoot, "desktop/renderer/design") } = {}) {
  const path = await resolveDesignPath(selection);
  const bytes = await readFile(path);
  const config = JSON.parse(bytes);
  const structure = await loadStructure(config.structure);
  const { errors, warnings } = validateDesign(config, structure);
  if (errors.length) throw new Error(`Design ${path} is invalid:\n${errors.map((error) => `  ${error.code}: ${error.message}`).join("\n")}`);
  const fonts = await loadDesignFonts(structure);
  const source = path.slice(repositoryRoot.length);
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(resolve(outputDirectory, "design.css"), designCss(config, source, fonts));
  for (const file of fonts.flatMap((font) => font.files)) {
    const target = resolve(outputDirectory, "..", file.path);
    await mkdir(resolve(target, ".."), { recursive: true });
    await writeFile(target, file.bytes);
  }
  console.log(`design: ${config.name} (${source}, sha256 ${sha256(bytes).slice(0, 12)}, ${warnings.length} floor warnings)`);
  return { path, sha256: sha256(bytes), files: ["design/design.css", ...fonts.flatMap((font) => font.files.map((file) => file.path))] };
}
