// Generates the renderer's design tokens from a design config (design-config-plan.md §2).
// RELAYER_DESIGN selects a config by id (designs/<id>.json) or path; otherwise designs/default names it.
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadStructure, validateDesign } from "./validate.mjs";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));

export async function resolveDesignPath(selection = process.env.RELAYER_DESIGN) {
  const id = selection || (await readFile(resolve(repositoryRoot, "designs/default"), "utf8")).trim();
  return id.endsWith(".json") ? resolve(process.env.INIT_CWD ?? process.cwd(), id) : resolve(repositoryRoot, "designs", `${id}.json`);
}

export function designCss(config, source) {
  const block = (mode) => [
    ...Object.entries(config.palette.roles).map(([role, value]) => `--${role}:${value[mode]}`),
    ...Object.entries(config.palette.families).flatMap(([id, family]) => [
      `--family-${id}:${family[mode]}`,
      `--family-${id}-icon:${family[`${mode}Icon`]}`,
    ]),
    `color-scheme:${mode}`,
  ].join(";");
  return `/* Generated by scripts/design/build.mjs from ${source}. Do not edit. */\n`
    + `:root{${block("dark")}}\n:root[data-theme="light"]{${block("light")}}\n`;
}

export async function buildDesign({ selection, outputDirectory = resolve(repositoryRoot, "desktop/renderer/design") } = {}) {
  const path = await resolveDesignPath(selection);
  const bytes = await readFile(path);
  const config = JSON.parse(bytes);
  const { errors, warnings } = validateDesign(config, await loadStructure(config.structure));
  if (errors.length) throw new Error(`Design ${path} is invalid:\n${errors.map((error) => `  ${error.code}: ${error.message}`).join("\n")}`);
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  const source = path.slice(repositoryRoot.length);
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(resolve(outputDirectory, "design.css"), designCss(config, source));
  console.log(`design: ${config.name} (${source}, sha256 ${sha256.slice(0, 12)}, ${warnings.length} floor warnings)`);
  return { path, sha256, files: ["design/design.css"] };
}
